### ISSUE TITLE
Cannot decrypt...

### ISSUE THREAD

**Issue by webcare-live** [jordanbtucker/odrive-crypt#1]
Hello jordanbtucker!
Can you do a video tutorial please, in order to share how to decrypt encrypted files with odrive?
I tried to decrypt like you wrote here, but its not working for me. Im sure that im doing wrong. 
The main reason I have asked you about video tutorial, is that I'm newbie in order to work with command prompt, and any programming language. 
I'm using Windows 10.
Help me please, thanks.

![image](https://cloud.githubusercontent.com/assets/14162372/23826522/44cbd1e2-06a6-11e7-8ca4-b0416f8cd66a.png)

**Comment by webcare-live** [comment]
(sorry for my little English)
I'm a video editor. 
If you will have time, and if you want to record your screen in order to do a tutorial, I can help you to edit that video.
I think that will be a good start for people like me.

**Comment by jordanbtucker** [comment]
You followed the instructions correctly. This was a error in the code.

Fixed in [v0.0.4](https://github.com/jordanbtucker/odrive-crypt/releases/tag/v0.0.4)

Please run `npm install -g odrive-crypt@0.0.4`, then try again.
